classDiagram
    class C_0010942968540697269095["Texture"]
    class C_0010942968540697269095 {
        +Texture(const std::string & path, GLenum texType, GLenum slot, GLenum format, GLenum pixelType) void
        +Texture(const Texture &) void
        +Texture(Texture && other) void
        +~Texture() void
        +operator=(const Texture &) Texture &
        +operator=(Texture && other) Texture &
        +Bind(GLuint unit) [const] void
        +Unbind() [const] void
        +ID : GLuint
        -type : GLuint
    }
    class C_0014899929896336503560["Shader"]
    class C_0014899929896336503560 {
        +Shader(const std::string & vertexFile, const std::string & fragmentFile) void
        +Shader(const Shader &) void
        +Shader(Shader && other) void
        +~Shader() void
        +operator=(const Shader &) Shader &
        +operator=(Shader && other) Shader &
        +Activate() [const] void
        +AttachTextureUnit(const GLuint textureID, const std::string & uniform) void
        +SetMat4(const std::string & name, const glm::mat4 & value) void
        +SetVec3(const std::string & name, const glm::vec3 & value) void
        +SetVec4(const std::string & name, const glm::vec4 & value) void
        +ID : GLuint
    }
    class C_0014704110374031903259["Vertex"]
    class C_0014704110374031903259 {
        +color : glm::vec3
        +normal : glm::vec3
        +position : glm::vec3
        +texCoords : glm::vec2
    }
    class C_0006077809002304625189["VBO"]
    class C_0006077809002304625189 {
        +VBO(const std::vector&lt;Vertex&gt; & vertices, GLenum usage) void
        +VBO(const VBO &) void
        +VBO(VBO && other) void
        +~VBO() void
        +operator=(const VBO &) VBO &
        +operator=(VBO && other) VBO &
        +Bind() [const] void
        +Unbind() [const] void
        +ID : GLuint
        -byteSize_ : std::size_t
        -usage_ : GLenum
    }
    class C_0005533647331416267481["VAO"]
    class C_0005533647331416267481 {
        +VAO() void
        +VAO(const VAO &) void
        +VAO(VAO && other) void
        +~VAO() void
        +operator=(const VAO &) VAO &
        +operator=(VAO && other) VAO &
        +Bind() [const] void
        +LinkAttrib(const VBO & VBO, GLuint layout, GLuint numComponent, GLenum type, GLsizeiptr stride, void * offset) [const] void
        +Unbind() [const] void
        +ID : GLuint
    }
    class C_0004105051469622735371["EBO"]
    class C_0004105051469622735371 {
        +EBO(const std::vector&lt;GLuint&gt; & indices, GLenum usage) void
        +EBO(const EBO &) void
        +EBO(EBO && other) void
        +~EBO() void
        +operator=(const EBO &) EBO &
        +operator=(EBO && other) EBO &
        +Bind() [const] void
        +Unbind() [const] void
        +Count : GLsizei
        +ID : GLuint
    }
    class C_0005049148943034209802["Camera"]
    class C_0005049148943034209802 {
        +Camera(int width, int height, glm::vec3 position) void
        +ProcessInput(GLFWwindow * window) void
        +SetUniformMatrix(Shader & shader, const std::string & uniform) void
        +SetViewportSize(int width, int height) void
        +UpdateMatrix(float FOVdeg, float nearPlane, float farPlane) void
        +Front : glm::vec3
        +MouseSensitivity : float
        +MoveSpeed : float
        +Position : glm::vec3
        +ScreenHeight : int
        +ScreenWidth : int
        +Up : glm::vec3
        -cameraMatrix_ : glm::mat4
        -isFirstClick_ : bool
    }
    class C_0013865567801987631274["Mesh"]
    class C_0013865567801987631274 {
        +Mesh(const std::vector&lt;Vertex&gt; & vertices, const std::vector&lt;GLuint&gt; & indices, std::vector&lt;std::unique_ptr&lt;Texture&gt;&gt; && textures, GLenum usage) void
        +Mesh(const Mesh &) void
        +Mesh(Mesh && other) void
        +~Mesh() void
        +operator=(const Mesh &) Mesh &
        +operator=(Mesh && other) Mesh &
        +Draw(const Shader & shader, const Camera & camare) [const] void
        +SetTexture(const Texture & texture) void
        -ebo_ : EBO
        -indices_ : std::vector&lt;GLuint&gt;
        -textures_ : std::vector&lt;std::unique_ptr&lt;Texture&gt;&gt;
        -vao_ : VAO
        -vbo_ : VBO
        -vertices_ : std::vector&lt;Vertex&gt;
    }
    C_0006077809002304625189 ..> C_0014704110374031903259 : 
    C_0005533647331416267481 ..> C_0006077809002304625189 : 
    C_0005049148943034209802 ..> C_0014899929896336503560 : 
    C_0013865567801987631274 ..> C_0014899929896336503560 : 
    C_0013865567801987631274 ..> C_0005049148943034209802 : 
    C_0013865567801987631274 o-- C_0005533647331416267481 : -vao_
    C_0013865567801987631274 o-- C_0006077809002304625189 : -vbo_
    C_0013865567801987631274 o-- C_0004105051469622735371 : -ebo_
    C_0013865567801987631274 o-- C_0010942968540697269095 : -textures_
    C_0013865567801987631274 o-- C_0014704110374031903259 : -vertices_

%% Generated with clang-uml, version 0.6.2-25-g5e2993e
%% LLVM version Debian clang version 19.1.7 (3+b1)
