classDiagram
    class C_0010942968540697269095["Texture"]
    class C_0010942968540697269095 {
        +Texture(const std::string & path, GLenum texType, GLenum slot, GLenum format, GLenum pixelType) void
        +Texture(const Texture &) void
        +Texture(Texture && other) void
        +~Texture() void
        +operator=(const Texture &) Texture &
        +operator=(Texture && other) Texture &
        +Bind(GLuint unit) [const] void
        +Unbind() [const] void
        +ID : GLuint
        -type_ : GLuint
    }
    class C_0014899929896336503560["Shader"]
    class C_0014899929896336503560 {
        +Shader(const std::string & vertexFile, const std::string & fragmentFile) void
        +Shader(const Shader &) void
        +Shader(Shader && other) void
        +~Shader() void
        +operator=(const Shader &) Shader &
        +operator=(Shader && other) Shader &
        +Activate() [const] void
        +AttachTextureUnit(const GLuint textureID, const std::string & uniform) [const] void
        +SetMat4(const std::string & name, const glm::mat4 & value) [const] void
        +SetVec3(const std::string & name, const glm::vec3 & value) [const] void
        +SetVec4(const std::string & name, const glm::vec4 & value) [const] void
        +ID : GLuint
    }
    class C_0005049148943034209802["Camera"]
    class C_0005049148943034209802 {
        +Camera(int width, int height, glm::vec3 position) void
        +ProcessInput(GLFWwindow * window) void
        +SetUniformMatrix(const Shader & shader, const std::string & uniform) [const] void
        +SetViewportSize(int width, int height) void
        +UpdateMatrix(float FOVdeg, float nearPlane, float farPlane) void
        +Front : glm::vec3
        +MouseSensitivity : float
        +MoveSpeed : float
        +Position : glm::vec3
        +ScreenHeight : int
        +ScreenWidth : int
        +Up : glm::vec3
        -cameraMatrix_ : glm::mat4
        -isFirstClick_ : bool
    }
    class C_0005533647331416267481["VAO"]
    class C_0005533647331416267481 {
        +VAO() void
        +VAO(const VAO &) void
        +VAO(VAO && other) void
        +~VAO() void
        +operator=(const VAO &) VAO &
        +operator=(VAO && other) VAO &
        +Bind() [const] void
        +LinkAttrib(GLuint vboID, GLuint layout, GLuint numComponent, GLenum type, GLsizeiptr stride, void * offset, bool isInteger = false) [const] void
        +Unbind() [const] void
        +ID : GLuint
    }
    class C_0015118057123430156612["VBO&lt;VertexT&gt;"]
    class C_0015118057123430156612 {
        +VBO(const std::vector&lt;VertexT&gt; & vertices, GLenum usage) void
        +VBO(const VBO&lt;VertexT&gt; &) void
        +VBO(VBO&lt;VertexT&gt; && other) void
        +~VBO() void
        +operator=(const VBO&lt;VertexT&gt; &) VBO&lt;VertexT&gt; &
        +operator=(VBO&lt;VertexT&gt; && other) VBO&lt;VertexT&gt; &
        +Bind() [const] void
        +Unbind() [const] void
        +Update(const std::vector&lt;VertexT&gt; & vertices) void
        +ID : GLuint
        -byteSize_ : std::size_t
        -usage_ : GLenum
    }
    class C_0004105051469622735371["EBO"]
    class C_0004105051469622735371 {
        +EBO(const std::vector&lt;GLuint&gt; & indices, GLenum usage) void
        +EBO(const EBO &) void
        +EBO(EBO && other) void
        +~EBO() void
        +operator=(const EBO &) EBO &
        +operator=(EBO && other) EBO &
        +Bind() [const] void
        +Unbind() [const] void
        +Update(const std::vector&lt;GLuint&gt; & indices) void
        +Count : GLsizei
        +ID : GLuint
        -usage_ : GLenum
    }
    class C_0001873370130499785759["ChunkVertex"]
    class C_0001873370130499785759 {
        +ao : uint8_t
        +normal : glm::vec3
        +position : glm::vec3
        +texCoords : glm::vec2
        +texLayer : uint8_t
    }
    class C_0002773998954947599944["MeshData"]
    class C_0002773998954947599944 {
        +Clear() void
        +Empty() [const] bool
        +indices : std::vector&lt;GLuint&gt;
        +vertices : std::vector&lt;ChunkVertex&gt;
    }
    class C_0009727957313001807244["VBO&lt;ChunkVertex&gt;"]
    class C_0009727957313001807244 {
    }
    class C_0011116618673378011020["ChunkMesh"]
    class C_0011116618673378011020 {
        +ChunkMesh() [default] void
        +ChunkMesh(const ChunkMesh &) void
        +ChunkMesh(ChunkMesh &&) [default] void
        +operator=(const ChunkMesh &) ChunkMesh &
        +operator=(ChunkMesh &&) [default] ChunkMesh &
        +Draw() [const] void
        +IndexCount() [const] GLuint
        +Upload(MeshData && data) void
        -ebo_ : std::unique_ptr&lt;EBO&gt;
        -indexCount_ : GLuint
        -vao_ : VAO
        -vbo_ : std::unique_ptr&lt;VBO&lt;ChunkVertex&gt;&gt;
    }
    class C_0016875631551870229693["BlockType"]
    class C_0016875631551870229693 {
        <<enumeration>>
        Air
        Grass
        Dirt
        Stone
    }
    class C_0001417863006499570610["ChunkCoord"]
    class C_0001417863006499570610 {
        +operator==(const ChunkCoord & o) [const] bool
        +x : int
        +z : int
    }
    class C_0004280677657916169007["ChunkCoordHash"]
    class C_0004280677657916169007 {
        +operator()(const ChunkCoord & c) [const] std::size_t
    }
    class C_0002305738170309990645["ChunkState"]
    class C_0002305738170309990645 {
        <<enumeration>>
        Empty
        Generated
        MeshReady
        Uploaded
        Dirty
    }
    class C_0004761464329442714065["ChunkNeighbors"]
    class C_0004761464329442714065 {
        +nx : std::shared_ptr&lt;const Chunk&gt;
        +nz : std::shared_ptr&lt;const Chunk&gt;
        +px : std::shared_ptr&lt;const Chunk&gt;
        +pz : std::shared_ptr&lt;const Chunk&gt;
    }
    class C_0003408262556741368811["Chunk"]
    class C_0003408262556741368811 {
        +Chunk(ChunkCoord coord) void
        -BlockAt(int x, int y, int z) BlockType &
        -BlockAt(int x, int y, int z) [const] const BlockType &
        +BuildMesh(const ChunkNeighbors & neighbors = &lbrace;&rbrace;) void
        +Coord() [const] ChunkCoord
        +Generate() void
        +GetBlock(int x, int y, int z) [const] BlockType
        +MarkDirty() void
        +Render(const Shader & shader, const Camera & camera) [const] void
        +SetBlock(int x, int y, int z, BlockType type) void
        +State() [const] ChunkState
        +UploadIfReady() void
        -blocks_ : std::unique_ptr&lt;BlockType[]&gt;
        -chunkMesh_ : ChunkMesh
        -coord_ : ChunkCoord
        -pendingMesh_ : MeshData
        -state_ : std::atomic&lt;ChunkState&gt;
        -textures_ : std::vector&lt;std::unique_ptr&lt;Texture&gt;&gt;
    }
    class C_0009584862300044083326["ChunkManager"]
    class C_0009584862300044083326 {
        +ChunkManager(int viewDistance = 8) void
        +~ChunkManager() void
        -DrainPendingDeletes() void
        +EnqueueWork(std::function&lt;void &lpar;&rpar;&gt; fn) void
        +GatherNeighbors(ChunkCoord coord) [const] ChunkNeighbors
        +GetChunk(ChunkCoord coord) [const] std::shared_ptr&lt;const Chunk&gt;
        -MakeChunk(ChunkCoord coord) std::shared_ptr&lt;Chunk&gt;
        +Update(const glm::vec3 & cameraPos, const Shader & shader, const Camera & camera) void
        +WorkerLoop() void
        -blockTexturePath_ : std::string
        -chunksMutex_ : std::mutex
        -chunks_ : std::unordered_map&lt;ChunkCoord,std::shared_ptr&lt;Chunk&gt;,ChunkCoordHash&gt;
        -deleteMutex_ : std::mutex
        -maxUploadsPerFrame_ : int
        -pendingDeletes_ : std::vector&lt;Chunk *&gt;
        -stopping_ : bool
        -uploadMutex_ : std::mutex
        -uploadQueue_ : std::queue&lt;ChunkCoord&gt;
        -viewDistance_ : int
        -workCV_ : std::condition_variable
        -workMutex_ : std::mutex
        -workQueue_ : std::queue&lt;std::function&lt;void &lpar;&rpar;&gt;&gt;
        -workers_ : std::vector&lt;std::thread&gt;
    }
    class C_0014704110374031903259["Vertex"]
    class C_0014704110374031903259 {
        +color : glm::vec3
        +normal : glm::vec3
        +position : glm::vec3
        +texCoords : glm::vec2
    }
    class C_0007974188475117411548["VBO&lt;Vertex&gt;"]
    class C_0007974188475117411548 {
    }
    class C_0013865567801987631274["Mesh"]
    class C_0013865567801987631274 {
        +Mesh(const std::vector&lt;Vertex&gt; & vertices, const std::vector&lt;GLuint&gt; & indices, std::vector&lt;std::unique_ptr&lt;Texture&gt;&gt; && textures, GLenum usage) void
        +Mesh(const Mesh &) void
        +Mesh(Mesh && other) void
        +~Mesh() void
        +operator=(const Mesh &) Mesh &
        +operator=(Mesh && other) Mesh &
        +Draw(const Shader & shader, const Camera & camare) [const] void
        +IndexCount() [const] GLuint
        +SetTexture(const Texture & texture) void
        +Upload(MeshData && meshData) void
        -ebo_ : EBO
        -indices_ : std::vector&lt;GLuint&gt;
        -textures_ : std::vector&lt;std::unique_ptr&lt;Texture&gt;&gt;
        -vao_ : VAO
        -vbo_ : VBO&lt;Vertex&gt;
        -vertices_ : std::vector&lt;Vertex&gt;
    }
    C_0005049148943034209802 ..> C_0014899929896336503560 : 
    C_0002773998954947599944 o-- C_0001873370130499785759 : +vertices
    C_0009727957313001807244 ..> C_0001873370130499785759 : 
    C_0009727957313001807244 ..|> C_0015118057123430156612 : 
    C_0011116618673378011020 ..> C_0002773998954947599944 : 
    C_0011116618673378011020 o-- C_0005533647331416267481 : -vao_
    C_0011116618673378011020 o-- C_0009727957313001807244 : -vbo_
    C_0011116618673378011020 o-- C_0004105051469622735371 : -ebo_
    C_0004280677657916169007 ..> C_0001417863006499570610 : 
    C_0004761464329442714065 --> C_0003408262556741368811 : +px
    C_0004761464329442714065 --> C_0003408262556741368811 : +nx
    C_0004761464329442714065 --> C_0003408262556741368811 : +pz
    C_0004761464329442714065 --> C_0003408262556741368811 : +nz
    C_0003408262556741368811 ..> C_0004761464329442714065 : 
    C_0003408262556741368811 ..> C_0014899929896336503560 : 
    C_0003408262556741368811 ..> C_0005049148943034209802 : 
    C_0003408262556741368811 o-- C_0001417863006499570610 : -coord_
    C_0003408262556741368811 o-- C_0002305738170309990645 : -state_
    C_0003408262556741368811 o-- C_0016875631551870229693 : -blocks_
    C_0003408262556741368811 o-- C_0011116618673378011020 : -chunkMesh_
    C_0003408262556741368811 o-- C_0010942968540697269095 : -textures_
    C_0003408262556741368811 o-- C_0002773998954947599944 : -pendingMesh_
    C_0009584862300044083326 ..> C_0014899929896336503560 : 
    C_0009584862300044083326 ..> C_0005049148943034209802 : 
    C_0009584862300044083326 ..> C_0004761464329442714065 : 
    C_0009584862300044083326 --> C_0003408262556741368811 : -pendingDeletes_
    C_0009584862300044083326 o-- C_0001417863006499570610 : -chunks_
    C_0009584862300044083326 o-- C_0003408262556741368811 : -chunks_
    C_0009584862300044083326 o-- C_0001417863006499570610 : -uploadQueue_
    C_0007974188475117411548 ..> C_0014704110374031903259 : 
    C_0007974188475117411548 ..|> C_0015118057123430156612 : 
    C_0013865567801987631274 ..> C_0014899929896336503560 : 
    C_0013865567801987631274 ..> C_0005049148943034209802 : 
    C_0013865567801987631274 ..> C_0002773998954947599944 : 
    C_0013865567801987631274 o-- C_0005533647331416267481 : -vao_
    C_0013865567801987631274 o-- C_0007974188475117411548 : -vbo_
    C_0013865567801987631274 o-- C_0004105051469622735371 : -ebo_
    C_0013865567801987631274 o-- C_0010942968540697269095 : -textures_
    C_0013865567801987631274 o-- C_0014704110374031903259 : -vertices_

%% Generated with clang-uml, version 0.6.2-25-g5e2993e
%% LLVM version Debian clang version 19.1.7 (3+b1)
